dist: xenial
language: python
cache: pip
notifications:
  email: false
sudo: true

python:
  - "3.7"
install:
  - pip install pillow
script:
  - python -m compileall .
  - black --check -N `git ls-files "*.py"`


